config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'orders#index'
  resources :orders, except: [:show] do
    get :to_in_progress
    get :to_finished
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  validates :name, :order_number, :state, presence: true
  validates :state, inclusion: {in: ['pending', 'in_progress', 'finished']}
  validates :order_number, uniqueness: true

  aasm column: 'state' do
    state :pending, initial: true
    state :in_progress
    state :finished

    event :finish do
      transitions from: [:in_progress], to: :finished
    end

    event :do do
      transitions from: [:pending], to: :in_progress
    end
  end

  def state_badge
    if pending?
      'badge-info'
    elsif in_progress?
      'badge-warning'
    elsif finished?
      'badge-success'
    end
  end

  def destroy
    errors.add(:base, 'não foi possível excluir o pedido') && return if !pending?
    super
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, except: [:index, :new, :create]

  def index
    @q = Order.ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @orders = @q.result.paginate(page: params[:page], per_page: 30)
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new order_params

    if @order.save
      flash[:success] = 'Pedido criado com sucesso.'
      redirect_to orders_path
    else
      flash.now[:danger] = 'Falha ao criar o pedido.'
      render :new
    end
  end

  def edit
  end

  def update
    if @order.update_attributes order_params
      flash[:success] = 'Pedido criado com sucesso.'
      redirect_to orders_path
    else
      flash[:danger] = 'Falha ao criar o pedido.'
      render :new
    end
  end

  def destroy
    if @order.destroy
      flash[:success] = 'Pedido excluído com sucesso.'
    else
      flash[:danger] = 'Erro ao excluir o pedido. Não é possível excluir pedidos concluídos ou em andamento.'
    end
    redirect_to orders_path
  end

  def to_in_progress
    @order.do!
    flash[:success] = 'Status do pedido alterado para Em progresso.'
    redirect_to orders_path
  end

  def to_finished
    @order.finish!
    flash[:success] = 'Status do pedido alterado para Concluído.'
    redirect_to orders_path
  end

  private
    def order_params
      params.require(:order).permit(:name, :order_number)
    end

    def set_order
      @order = Order.find(params[:id] || params[:order_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |type, msg|
  .alert{class: "alert-#{type == 'notice' ? 'info' : type}"}
    = msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SAPED - Sistema de Administração de Pedidos
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      %header
        %nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
          %a.navbar-brand{:href => "#"} Sistema de Administração de Pedidos
          %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
            %span.navbar-toggler-icon
          #navbarCollapse.collapse.navbar-collapse
            %ul.navbar-nav.mr-auto
              %li.nav-item.active
                %a.nav-link{:href => orders_path}
                  Gestão de pedidos
                  %span.sr-only (current)
              %li.nav-item
                = link_to('Sair', destroy_user_session_path, method: :delete, class: 'nav-link')
    %main.flex-shrink-0.mt-4{:role => "main"}
      .container
        .mt-100
          = render '/layouts/flash'
          = yield
    %footer.footer.mt-auto.py-3
      .container
        %span.text-muted= "Copyright © #{Date.today.year}."

app/views/orders/_filters.html.haml
%h5 Filtrar por:
= search_form_for @q do |f|
  .row
    .col-sm-4
      %label.label-control Nome ou número do pedido
      = f.search_field :name_or_order_number_cont, class: 'form-control'
    .col-sm-4
      %label.label-control Status do pedido
      = f.select :state_cont, options_for_select([:pending, :in_progress, :finished].map{|s| [t("orders.states.#{s}"), s] }, selected: @q.state_cont), {include_blank: true}, class: 'form-control'
    .col-sm-4
      = f.button 'Filtrar', class: 'btn btn-secondary', style: 'margin-top: 32px'

app/views/orders/_form.html.haml
- if @order.persisted?
  - if @order.pending?
    = link_to 'Fazer pedido', order_to_in_progress_path(@order), class: 'btn btn-sm btn-success float-right',
                                                                 data: {confirm: 'Tem certeza que deseja alterar o status desse pedido para a fazer?'}
  - elsif @order.in_progress?
    = link_to 'Concluir pedido', order_to_finished_path(@order), class: 'btn btn-sm btn-success float-right',
                                                               data: {confirm: 'Tem certeza que deseja alterar o status desse pedido para a concluído?'}

.mt-4
  = simple_form_for @order do |f|
    = f.input :name, label: 'Descrição do pedido'
    = f.input :order_number, label: 'Número do pedido'
    = f.input :state, label: 'Estado', input_html: {value: t("orders.states.#{@order.state}"), disabled: :disabled}
    .row
      .col-sm-12
        = f.button :submit, value: 'Salvar pedido', class: 'btn btn-primary float-right'
        = link_to 'Voltar', orders_path, class: 'btn btn-light float-right mr-4'

app/views/orders/edit.html.haml
%h3 Editar pedido

= render 'form'

app/views/orders/index.html.haml
%h3
  Gestão de pedidos
  = link_to new_order_path, class: 'btn btn-primary float-right' do
    + Novo pedido
= render 'filters'
- if @orders.any?
  .table-responsive
    %table.table.table-striped.table-bordered.mt-4
      %tr
        %th= sort_link(@q, :order_number, 'Número do pedido')
        %th= sort_link(@q, :state, 'Status')
        %th= sort_link(@q, :name, 'Descrição')
        %th= sort_link(@q, :created_at, 'Data de criação')
        %th= sort_link(@q, :updated_at, 'Última atualização')
        %th
      - @orders.each do |order|
        %tr
          %td= order.order_number
          %td
            %span.badge{class: order.state_badge}= t("orders.states.#{order.state}")
          %td= order.name
          %td= l order.created_at, format: :short
          %td= l order.updated_at, format: :short
          %td
            - if order.pending?
              = link_to 'Fazer pedido', order_to_in_progress_path(order), class: 'btn btn-sm btn-success',
                                                                          data: {confirm: 'Tem certeza que deseja alterar o status desse pedido para a fazer?'}
            - elsif order.in_progress?
              = link_to 'Concluir pedido', order_to_finished_path(order), class: 'btn btn-sm btn-success',
                                                                          data: {confirm: 'Tem certeza que deseja alterar o status desse pedido para concluído?'}
            = link_to 'Editar', edit_order_path(order), class: 'btn btn-sm btn-warning'
            - if order.pending?
              = link_to 'Excluir', order_path(order), class: 'btn btn-sm btn-danger',
                                                    data: {confirm: 'Tem certeza que deseja excluir?', method: :delete}
  .float-right= will_paginate @orders, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

- else
  .mt-4 Nenhum pedido encontrado.

app/views/orders/new.html.haml
%h3 Criar pedido

= render 'form'